/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.miniMundo.Presentation.Desktop;

import br.edu.ifnmg.miniMundo.DomainModel.CompraProduto;
import br.edu.ifnmg.miniMundo.DomainModel.ErroValidacaoException;
import br.edu.ifnmg.miniMundo.DomainModel.Fornecedor;
import br.edu.ifnmg.miniMundo.DomainModel.Funcionario;
import br.edu.ifnmg.miniMundo.DomainModel.ListaItens;
import br.edu.ifnmg.miniMundo.DomainModel.Produto;
import br.edu.ifnmg.miniMundo.Persistence.FornecedorRepositorio;
import br.edu.ifnmg.miniMundo.Persistence.ProdutoRepositorio;
import br.edu.ifnmg.miniMundo.Persistence.ComprasRepositorio;
import br.edu.ifnmg.miniMundo.Persistence.EstoqueRepositorio;
import br.edu.ifnmg.miniMundo.Persistence.FuncionarioRepositorio;
import static br.edu.ifnmg.miniMundo.Presentation.Desktop.MenuGerenciamento.Desktop;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Edlâine
 */
public class CompraFornecedor extends javax.swing.JInternalFrame {

    /**
     * Creates new form CompraFornecedor
     */
    Produto produto;
    ProdutoRepositorio repo_produto;
    Fornecedor fornec;
    FuncionarioRepositorio repo_func;
    FornecedorRepositorio repo_fornec;
    CompraProduto compra;
    ComprasRepositorio repo_compra;
    EstoqueRepositorio repo_estoque;
    private Funcionario funcionario;

    public void atualizaCBX(){
        List<Fornecedor> fornecedores;
        fornecedores = repo_fornec.Buscar(null);
        ComboBoxModel<Fornecedor> model_fornec =
            new DefaultComboBoxModel<>(new Vector (fornecedores) );
        cbxFornecedor.setModel(model_fornec);    
    }
    
    public CompraFornecedor(Funcionario funcionario) {
        produto = new Produto();
        repo_produto = new ProdutoRepositorio();
        repo_func = new FuncionarioRepositorio();
        repo_fornec = new FornecedorRepositorio();
        compra = new CompraProduto();
        repo_compra = new ComprasRepositorio();
        repo_estoque = new EstoqueRepositorio();
        initComponents();
        atualizaCBX();
        this.funcionario = funcionario;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblInformacoes = new javax.swing.JLabel();
        lblFornecedor = new javax.swing.JLabel();
        cbxFornecedor = new javax.swing.JComboBox<>();
        btnNovoFornecedor = new javax.swing.JButton();
        lblCodProduto = new javax.swing.JLabel();
        txtIdProduto = new javax.swing.JTextField();
        lblDescricao = new javax.swing.JLabel();
        txtDescricaoProduto = new javax.swing.JTextField();
        btnBuscarProd = new javax.swing.JButton();
        btnNovoProduto = new javax.swing.JButton();
        btnEditarProduto = new javax.swing.JButton();
        lblQntd = new javax.swing.JLabel();
        txtQntdCompra = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabResultado = new javax.swing.JTable();
        btnAtualiza = new javax.swing.JButton();
        txtValorTotal = new javax.swing.JTextField();
        lblPrecoFinal = new javax.swing.JLabel();
        btnFinalizar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setClosable(true);
        setTitle("Mini Mundo Supermecados - Compra de Produtos");

        lblInformacoes.setText("Preencha as informações a seguir para prosseguir:");

        lblFornecedor.setText("Fornecedor:");

        btnNovoFornecedor.setText("NOVO FORNECEDOR");
        btnNovoFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoFornecedorActionPerformed(evt);
            }
        });

        lblCodProduto.setText("Cód. Produto:");

        txtIdProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProdutoActionPerformed(evt);
            }
        });

        lblDescricao.setText("Descrição do Produto:");

        btnBuscarProd.setText("BUSCAR");
        btnBuscarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProdActionPerformed(evt);
            }
        });

        btnNovoProduto.setText("NOVO PRODUTO");
        btnNovoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoProdutoActionPerformed(evt);
            }
        });

        btnEditarProduto.setText("MODIFICAR");
        btnEditarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarProdutoActionPerformed(evt);
            }
        });

        lblQntd.setText("Insira a quantidade comprada:");

        btnAdicionar.setText("ADICIONAR");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnRemover.setText("REMOVER");

        tabResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição", "Quantidade ", "Valor Unitário"
            }
        ));
        jScrollPane1.setViewportView(tabResultado);

        btnAtualiza.setText("ATUALIZAR");
        btnAtualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizaActionPerformed(evt);
            }
        });

        lblPrecoFinal.setText("VALOR FINAL:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblPrecoFinal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblQntd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtQntdCompra))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCodProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnBuscarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnEditarProduto))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(lblDescricao)))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDescricaoProduto)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(btnAdicionar)
                                        .addGap(25, 25, 25)
                                        .addComponent(btnRemover))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(btnNovoProduto)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblFornecedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblInformacoes))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnNovoFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAtualiza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInformacoes)
                    .addComponent(btnAtualiza, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFornecedor)
                    .addComponent(cbxFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovoFornecedor))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodProduto)
                    .addComponent(txtIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescricao)
                    .addComponent(txtDescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarProd)
                    .addComponent(btnEditarProduto)
                    .addComponent(btnNovoProduto))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQntd)
                    .addComponent(txtQntdCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionar)
                    .addComponent(btnRemover))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecoFinal))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Compra", jPanel1);

        jTabbedPane1.addTab("Compra de Produtos", jTabbedPane2);

        btnFinalizar.setText("FINALIZAR COMPRA");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addGap(56, 56, 56)
                        .addComponent(btnFinalizar))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFinalizar)
                    .addComponent(btnCancelar))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoFornecedorActionPerformed
        // TODO add your handling code here:
        CadastrarFornecedor tela = new CadastrarFornecedor();
        
        Desktop.add(tela);
        tela.setVisible(true);        
    }//GEN-LAST:event_btnNovoFornecedorActionPerformed

    private void txtIdProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProdutoActionPerformed

    private void btnEditarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarProdutoActionPerformed
        // TODO add your handling code here:
        EditarProduto tela = new EditarProduto();
        
        Desktop.add(tela);
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnEditarProdutoActionPerformed

    private void btnBuscarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProdActionPerformed
        // TODO add your handling code here:
        produto = new Produto();
        
         try {
            if(txtIdProduto.getText().length() > 0)
                produto.setId(Integer.parseInt(txtIdProduto.getText() ));
            if(txtDescricaoProduto.getText().length() > 0)
                produto.setDescricao(txtDescricaoProduto.getText());
            
        }catch(ErroValidacaoException ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        try {
            produto = repo_produto.PreencheProduto(produto);
            //pega do banco de dados e joga para o text field
            if(produto != null){
                this.txtDescricaoProduto.setText(produto.getDescricao());
                this.txtIdProduto.setText(String.valueOf( produto.getId() ));
            }
            else
                this.txtDescricaoProduto.setText("Produto Inexistente!");
                       
        } catch (SQLException ex) {
            Logger.getLogger(CompraFornecedor.class.getName()).log(Level.SEVERE, null, ex);
        }            
    }//GEN-LAST:event_btnBuscarProdActionPerformed

    private void btnNovoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoProdutoActionPerformed
        // TODO add your handling code here:
        CadastrarProduto tela = new CadastrarProduto();
        
        Desktop.add(tela);
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnNovoProdutoActionPerformed

    private void btnAtualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizaActionPerformed
        // TODO add your handling code here:
        atualizaCBX();
    }//GEN-LAST:event_btnAtualizaActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:
        produto = new Produto();
        
        produto.setId(Integer.parseInt(txtIdProduto.getText()));
        if(txtQntdCompra.getText().length() > 0)
            produto.setUnidComprada(Integer.parseInt(txtQntdCompra.getText() ));
        try {
            produto = repo_produto.Abrir(produto.getId());
            //pega do banco de dados e joga para o text field
            if(produto != null){
                if(produto.getUnidComprada() > 
                        Integer.parseInt(this.txtQntdCompra.getText())){
                    AdicaoItens(produto);
                    preencherTabela();
                    calcularPreco();
                    txtIdProduto.setText("");
                    txtDescricaoProduto.setText("");
                    txtQntdCompra.setText("");
                }
                else{
                    JOptionPane.showMessageDialog(null, "Quantidade Superior ao ESTOQUE!"); 
                    txtQntdCompra.setText("");
                }
            }
            else
                this.txtDescricaoProduto.setText("Produto Inexistente!");
                       
        } catch (ErroValidacaoException ex) {
            Logger.getLogger(CompraFornecedor.class.getName()).log(Level.SEVERE, null, ex);
        }            
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        //mostra msg de confirmação
        if (JOptionPane.showConfirmDialog(null, "Deseja realmente CANCELAR?",
            "Confirmar", JOptionPane.YES_NO_OPTION) == 0){
            dispose();
        }  
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        // TODO add your handling code here:
        CompraProduto compra = new CompraProduto();
        compra.setFornec((Fornecedor) cbxFornecedor.getSelectedItem());
        //compra.setFunc();
        if(this.repo_fornec.ChecarStatus(compra.getFornec().getId()) == 1){
            if(!this.compra.getItens().isEmpty()){
                ComprasRepositorio repo_compra = new ComprasRepositorio();
                compra.setFunc(funcionario);
                compra.getFornec();
                compra.setPreco_final(BigDecimal.
                        valueOf(Double.valueOf(txtValorTotal.getText())));
                
                try {
                    if(repo_compra.Salvar(compra) == true){
                        //listagem não funcional
                        repo_compra.ListagemItens(compra);
                        JOptionPane.showMessageDialog(null, "Finalizado com Sucesso!");
                        dispose();
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(CompraFornecedor.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else
                JOptionPane.showMessageDialog(null, "Lista de Compras Vazia!");
        }
        else
            JOptionPane.showMessageDialog(null, "Fornecedor Inativo!");

    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void preencherTabela(){
        //cria uma tabela vazia
        DefaultTableModel modelo = new DefaultTableModel();
        //adiciona coluna por coluna        
        modelo.addColumn("Descrição");
        modelo.addColumn("Quantidade");
        modelo.addColumn("Valor Unitário");
              
        //para cada item da lista
  
        List<ListaItens> itens = this.compra.getItens();
        for (ListaItens item: itens){
            //cria um vetor de linha
            Vector linha = new Vector();
            //adiciona linha por linha
            linha.add(item.getProduto());
            linha.add(item.getQnt());
            linha.add(item.getTotal());            
            //adiciona cada linha na tabela
            modelo.addRow(linha);
        }        
        //adiciona o modelo que é a minha tabela na tabela da interface
        tabResultado.setModel(modelo); 
    }
    
    public void AdicaoItens(Produto produto) throws ErroValidacaoException{
        ListaItens item = new ListaItens();
        
        item.setProduto(produto);
        item.setQnt(Integer.parseInt(txtQntdCompra.getText()));
        item.setTotal(produto.getPrecoCompra());
        
        this.compra.addItem(item);    
    }
    
    public void calcularPreco(){
        float preco = (float) 0.0;
        for(ListaItens item: compra.getItens())
            preco += item.getQnt() * item.getProduto().
                    getPrecoCompra().setScale(2, RoundingMode.DOWN).
                    floatValue();   
        txtValorTotal.setText(String.valueOf(preco));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAtualiza;
    private javax.swing.JButton btnBuscarProd;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditarProduto;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnNovoFornecedor;
    private javax.swing.JButton btnNovoProduto;
    private javax.swing.JButton btnRemover;
    private javax.swing.JComboBox<Fornecedor> cbxFornecedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lblCodProduto;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblFornecedor;
    private javax.swing.JLabel lblInformacoes;
    private javax.swing.JLabel lblPrecoFinal;
    private javax.swing.JLabel lblQntd;
    private javax.swing.JTable tabResultado;
    private javax.swing.JTextField txtDescricaoProduto;
    private javax.swing.JTextField txtIdProduto;
    private javax.swing.JTextField txtQntdCompra;
    private javax.swing.JTextField txtValorTotal;
    // End of variables declaration//GEN-END:variables
}
