/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.miniMundo.Presentation.Desktop;

import br.edu.ifnmg.miniMundo.DomainModel.ErroValidacaoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Edlâine
 */
public class MenuGerenciamento extends javax.swing.JFrame {
 
    //skip-grant-tables
    
    /**
     * Creates new form frmTelaInicial
     */
    public MenuGerenciamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        Desktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        lblMiniMundo1 = new javax.swing.JLabel();
        lblMiniMundo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuSistema = new javax.swing.JMenu();
        mnuSair = new javax.swing.JMenuItem();
        mnuCadastro = new javax.swing.JMenu();
        mnuCadCliente = new javax.swing.JMenuItem();
        mnuBuscarCliente = new javax.swing.JMenuItem();
        mnuEditarCliente = new javax.swing.JMenuItem();
        mnuFunc = new javax.swing.JMenu();
        mnuCadFUNC = new javax.swing.JMenuItem();
        mnuBuscarFunc = new javax.swing.JMenuItem();
        mnuEditarFunc = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mnuCadFornecedor = new javax.swing.JMenuItem();
        mnuBuscarFornec = new javax.swing.JMenuItem();
        mnuEditarFornecedor = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuCadProduto = new javax.swing.JMenuItem();
        mnuBuscarProduto = new javax.swing.JMenuItem();
        mnuEditarProduto = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuAquisicao = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnuVendas = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setTitle("Mini Mundo - Gerenciamento de Opções");
        setBackground(new java.awt.Color(255, 255, 255));

        Desktop.setBackground(new java.awt.Color(240, 240, 240));
        Desktop.setForeground(new java.awt.Color(240, 240, 240));
        Desktop.setPreferredSize(new java.awt.Dimension(1024, 780));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Seja Bem Vindo!");
        Desktop.add(jLabel1);
        jLabel1.setBounds(540, 200, 131, 22);

        lblMiniMundo1.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        lblMiniMundo1.setText("Mini Mundo ");
        Desktop.add(lblMiniMundo1);
        lblMiniMundo1.setBounds(510, 260, 197, 41);

        lblMiniMundo.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        lblMiniMundo.setText("Supermecados");
        Desktop.add(lblMiniMundo);
        lblMiniMundo.setBounds(500, 310, 200, 63);

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        mnuSistema.setText("Sistema");

        mnuSair.setText("Sair");
        mnuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuSairMouseClicked(evt);
            }
        });
        mnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSairActionPerformed(evt);
            }
        });
        mnuSistema.add(mnuSair);

        jMenuBar1.add(mnuSistema);

        mnuCadastro.setText("Cliente");
        mnuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastroActionPerformed(evt);
            }
        });

        mnuCadCliente.setText("Cadastro Cliente");
        mnuCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadClienteActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuCadCliente);

        mnuBuscarCliente.setText("Buscar Cliente");
        mnuBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBuscarClienteActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuBuscarCliente);

        mnuEditarCliente.setText("Editar Cliente");
        mnuEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEditarClienteActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuEditarCliente);

        jMenuBar1.add(mnuCadastro);

        mnuFunc.setText("Funcionário");

        mnuCadFUNC.setText("Cad Func");
        mnuCadFUNC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadFUNCActionPerformed(evt);
            }
        });
        mnuFunc.add(mnuCadFUNC);

        mnuBuscarFunc.setText("Buscar Func");
        mnuBuscarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBuscarFuncActionPerformed(evt);
            }
        });
        mnuFunc.add(mnuBuscarFunc);

        mnuEditarFunc.setText("Editar Func");
        mnuEditarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEditarFuncActionPerformed(evt);
            }
        });
        mnuFunc.add(mnuEditarFunc);

        jMenuBar1.add(mnuFunc);

        jMenu1.setText("Fornecedor");

        mnuCadFornecedor.setText("Cad Fornecedor");
        mnuCadFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadFornecedorActionPerformed(evt);
            }
        });
        jMenu1.add(mnuCadFornecedor);

        mnuBuscarFornec.setText("Buscar Fornecedor");
        mnuBuscarFornec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBuscarFornecActionPerformed(evt);
            }
        });
        jMenu1.add(mnuBuscarFornec);

        mnuEditarFornecedor.setText("Editar Fornecedor");
        mnuEditarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEditarFornecedorActionPerformed(evt);
            }
        });
        jMenu1.add(mnuEditarFornecedor);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Produto");

        mnuCadProduto.setText("Cad Produto");
        mnuCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadProdutoActionPerformed(evt);
            }
        });
        jMenu2.add(mnuCadProduto);

        mnuBuscarProduto.setText("Buscar Produto");
        mnuBuscarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBuscarProdutoActionPerformed(evt);
            }
        });
        jMenu2.add(mnuBuscarProduto);

        mnuEditarProduto.setText("Editar Produto");
        mnuEditarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEditarProdutoActionPerformed(evt);
            }
        });
        jMenu2.add(mnuEditarProduto);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Compra");

        mnuAquisicao.setText("Aquisicao de Produtos");
        mnuAquisicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAquisicaoActionPerformed(evt);
            }
        });
        jMenu3.add(mnuAquisicao);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Vendas");

        mnuVendas.setText("Efetuar Vendas");
        mnuVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVendasActionPerformed(evt);
            }
        });
        jMenu4.add(mnuVendas);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 1335, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getAccessibleContext().setAccessibleName("Menu Principal");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSairActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Deseja realmente SAIR?",
            "Confirmar", JOptionPane.YES_NO_OPTION) == 0){
            dispose();
        }
    }//GEN-LAST:event_mnuSairActionPerformed

    private void mnuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuCadastroActionPerformed

    private void mnuCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadClienteActionPerformed
        // TODO add your handling code here:
        CadastrarCliente tela = new CadastrarCliente();
        
        Desktop.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_mnuCadClienteActionPerformed

    private void mnuBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBuscarClienteActionPerformed
        // TODO add your handling code here:
        BuscarCliente tela = new BuscarCliente();
        
        Desktop.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_mnuBuscarClienteActionPerformed

    private void mnuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuSairMouseClicked
        // TODO add your handling code here:       
    }//GEN-LAST:event_mnuSairMouseClicked

    private void mnuCadFUNCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadFUNCActionPerformed
        // TODO add your handling code here:
        CadastrarFuncionario tela = new CadastrarFuncionario();
        
        Desktop.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_mnuCadFUNCActionPerformed

    private void mnuBuscarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBuscarFuncActionPerformed
        // TODO add your handling code here:
        BuscarFuncionario tela = new BuscarFuncionario();
        
        Desktop.add(tela);
        tela.setVisible(true);
        
    }//GEN-LAST:event_mnuBuscarFuncActionPerformed

    private void mnuCadFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadFornecedorActionPerformed
        // TODO add your handling code here:
        CadastrarFornecedor tela = new CadastrarFornecedor();
        
        Desktop.add(tela);
        tela.setVisible(true);
        
    }//GEN-LAST:event_mnuCadFornecedorActionPerformed

    private void mnuBuscarFornecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBuscarFornecActionPerformed
        // TODO add your handling code here:
        BuscarFornecedor tela = new BuscarFornecedor();
        
        Desktop.add(tela);
        tela.setVisible(true);
        
    }//GEN-LAST:event_mnuBuscarFornecActionPerformed

    private void mnuCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadProdutoActionPerformed
        // TODO add your handling code here:
        CadastrarProduto tela = new CadastrarProduto();
        
        Desktop.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_mnuCadProdutoActionPerformed

    private void mnuBuscarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBuscarProdutoActionPerformed
        // TODO add your handling code here:
        BuscarProduto tela = new BuscarProduto();
        
        Desktop.add(tela);
        tela.setVisible(true);        
    }//GEN-LAST:event_mnuBuscarProdutoActionPerformed

    private void mnuAquisicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAquisicaoActionPerformed
        // TODO add your handling code here:
        ValidacaoParaCompra tela = new ValidacaoParaCompra();
        
        Desktop.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_mnuAquisicaoActionPerformed

    private void mnuVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVendasActionPerformed
        // TODO add your handling code here:
        ValidarParaVendas tela = new ValidarParaVendas();
        
        Desktop.add(tela);
        tela.setVisible(true);
        
    }//GEN-LAST:event_mnuVendasActionPerformed

    private void mnuEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEditarClienteActionPerformed
        // TODO add your handling code here:
        EditarCliente tela = new EditarCliente();
        
        Desktop.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_mnuEditarClienteActionPerformed

    private void mnuEditarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEditarFuncActionPerformed
        // TODO add your handling code here:
        EditarFuncionario tela = new EditarFuncionario();
        
        Desktop.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_mnuEditarFuncActionPerformed

    private void mnuEditarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEditarFornecedorActionPerformed
        // TODO add your handling code here:
        EditarFornecedor tela = new EditarFornecedor();
        
        Desktop.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_mnuEditarFornecedorActionPerformed

    private void mnuEditarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEditarProdutoActionPerformed
        // TODO add your handling code here:
        EditarProduto tela = new EditarProduto();
        
        Desktop.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_mnuEditarProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGerenciamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGerenciamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGerenciamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGerenciamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>   
        //</editor-fold>
        //</editor-fold>   
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGerenciamento().setVisible(true);
            }
        });       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane Desktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel lblMiniMundo;
    private javax.swing.JLabel lblMiniMundo1;
    private javax.swing.JMenuItem mnuAquisicao;
    private javax.swing.JMenuItem mnuBuscarCliente;
    private javax.swing.JMenuItem mnuBuscarFornec;
    private javax.swing.JMenuItem mnuBuscarFunc;
    private javax.swing.JMenuItem mnuBuscarProduto;
    private javax.swing.JMenuItem mnuCadCliente;
    private javax.swing.JMenuItem mnuCadFUNC;
    private javax.swing.JMenuItem mnuCadFornecedor;
    private javax.swing.JMenuItem mnuCadProduto;
    private javax.swing.JMenu mnuCadastro;
    private javax.swing.JMenuItem mnuEditarCliente;
    private javax.swing.JMenuItem mnuEditarFornecedor;
    private javax.swing.JMenuItem mnuEditarFunc;
    private javax.swing.JMenuItem mnuEditarProduto;
    private javax.swing.JMenu mnuFunc;
    private javax.swing.JMenuItem mnuSair;
    private javax.swing.JMenu mnuSistema;
    private javax.swing.JMenuItem mnuVendas;
    // End of variables declaration//GEN-END:variables
}
