/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.miniMundo.Presentation.Desktop;

import br.edu.ifnmg.miniMundo.DomainModel.ErroValidacaoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Edlâine
 */
public class MenuGerenciamento extends javax.swing.JFrame {
 
    //skip-grant-tables
    
    /**
     * Creates new form frmTelaInicial
     */
    public MenuGerenciamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jMenuItem1 = new javax.swing.JMenuItem();
        lblMiniMundo = new javax.swing.JLabel();
        lblMiniMundo1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuSistema = new javax.swing.JMenu();
        mnuSair = new javax.swing.JMenuItem();
        mnuCadastro = new javax.swing.JMenu();
        mnuCadCliente = new javax.swing.JMenuItem();
        mnuBuscarCliente = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        mnuFunc = new javax.swing.JMenu();
        mnuCadFUNC = new javax.swing.JMenuItem();
        mnuBuscarFunc = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mnuCadFornecedor = new javax.swing.JMenuItem();
        mnuBuscarFornec = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuCadProduto = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setTitle("Mini Mundo - Gerenciamento de Opções");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        lblMiniMundo.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        lblMiniMundo.setText("Supermecados");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipady = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 77, 93, 59);
        getContentPane().add(lblMiniMundo, gridBagConstraints);

        lblMiniMundo1.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        lblMiniMundo1.setText("Mini Mundo ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 77, 0, 0);
        getContentPane().add(lblMiniMundo1, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Seja Bem Vindo!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(54, 105, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        mnuSistema.setText("Sistema");

        mnuSair.setText("Sair");
        mnuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuSairMouseClicked(evt);
            }
        });
        mnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSairActionPerformed(evt);
            }
        });
        mnuSistema.add(mnuSair);

        jMenuBar1.add(mnuSistema);

        mnuCadastro.setText("Cliente");
        mnuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastroActionPerformed(evt);
            }
        });

        mnuCadCliente.setText("Cadastro Cliente");
        mnuCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadClienteActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuCadCliente);

        mnuBuscarCliente.setText("Buscar Cliente");
        mnuBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBuscarClienteActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuBuscarCliente);

        jMenuItem2.setText("Editar Cliente");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mnuCadastro.add(jMenuItem2);

        jMenuBar1.add(mnuCadastro);

        mnuFunc.setText("Funcionário");

        mnuCadFUNC.setText("Cad Func");
        mnuCadFUNC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadFUNCActionPerformed(evt);
            }
        });
        mnuFunc.add(mnuCadFUNC);

        mnuBuscarFunc.setText("Buscar Func");
        mnuBuscarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBuscarFuncActionPerformed(evt);
            }
        });
        mnuFunc.add(mnuBuscarFunc);

        jMenuBar1.add(mnuFunc);

        jMenu1.setText("Fornecedor");

        mnuCadFornecedor.setText("Cad Fornecedor");
        mnuCadFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadFornecedorActionPerformed(evt);
            }
        });
        jMenu1.add(mnuCadFornecedor);

        mnuBuscarFornec.setText("Buscar Fornecedor");
        mnuBuscarFornec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBuscarFornecActionPerformed(evt);
            }
        });
        jMenu1.add(mnuBuscarFornec);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Produto");

        mnuCadProduto.setText("Cad Produto");
        mnuCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadProdutoActionPerformed(evt);
            }
        });
        jMenu2.add(mnuCadProduto);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        getAccessibleContext().setAccessibleName("Menu Principal");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSairActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Deseja realmente SAIR?",
            "Confirmar", JOptionPane.YES_NO_OPTION) == 0){
            dispose();
        }
    }//GEN-LAST:event_mnuSairActionPerformed

    private void mnuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuCadastroActionPerformed

    private void mnuCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadClienteActionPerformed
        // TODO add your handling code here:
        CadastrarCliente tela = new CadastrarCliente();
        
        this.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_mnuCadClienteActionPerformed

    private void mnuBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBuscarClienteActionPerformed
        // TODO add your handling code here:
        BuscarCliente tela = new BuscarCliente();
        
        this.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_mnuBuscarClienteActionPerformed

    private void mnuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuSairMouseClicked
        // TODO add your handling code here:       
    }//GEN-LAST:event_mnuSairMouseClicked

    private void mnuCadFUNCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadFUNCActionPerformed
        // TODO add your handling code here:
        CadastrarFuncionario tela = new CadastrarFuncionario();
        
        this.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_mnuCadFUNCActionPerformed

    private void mnuBuscarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBuscarFuncActionPerformed
        // TODO add your handling code here:
        BuscarFuncionario tela = new BuscarFuncionario();
        
        this.add(tela);
        tela.setVisible(true);
        
    }//GEN-LAST:event_mnuBuscarFuncActionPerformed

    private void mnuCadFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadFornecedorActionPerformed
        // TODO add your handling code here:
        CadastrarFornecedor tela = new CadastrarFornecedor();
        
        this.add(tela);
        tela.setVisible(true);
        
    }//GEN-LAST:event_mnuCadFornecedorActionPerformed

    private void mnuBuscarFornecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBuscarFornecActionPerformed
        // TODO add your handling code here:
        BuscarFornecedor tela = new BuscarFornecedor();
        
        this.add(tela);
        tela.setVisible(true);
        
    }//GEN-LAST:event_mnuBuscarFornecActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        ValidarEdicaoCliente tela = new ValidarEdicaoCliente();
        
        this.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void mnuCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadProdutoActionPerformed
        // TODO add your handling code here:
        CadastrarProduto tela = new CadastrarProduto();
        this.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_mnuCadProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGerenciamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGerenciamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGerenciamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGerenciamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>   
        //</editor-fold>
        //</editor-fold>   
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGerenciamento().setVisible(true);
            }
        });       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel lblMiniMundo;
    private javax.swing.JLabel lblMiniMundo1;
    private javax.swing.JMenuItem mnuBuscarCliente;
    private javax.swing.JMenuItem mnuBuscarFornec;
    private javax.swing.JMenuItem mnuBuscarFunc;
    private javax.swing.JMenuItem mnuCadCliente;
    private javax.swing.JMenuItem mnuCadFUNC;
    private javax.swing.JMenuItem mnuCadFornecedor;
    private javax.swing.JMenuItem mnuCadProduto;
    private javax.swing.JMenu mnuCadastro;
    private javax.swing.JMenu mnuFunc;
    private javax.swing.JMenuItem mnuSair;
    private javax.swing.JMenu mnuSistema;
    // End of variables declaration//GEN-END:variables
}
