/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.miniMundo.Presentation.Desktop;

import br.edu.ifnmg.miniMundo.DomainModel.Cliente;
import br.edu.ifnmg.miniMundo.DomainModel.ErroValidacaoException;
import br.edu.ifnmg.miniMundo.DomainModel.Funcionario;
import br.edu.ifnmg.miniMundo.DomainModel.Produto;
import br.edu.ifnmg.miniMundo.DomainModel.VendaProduto;
import br.edu.ifnmg.miniMundo.Persistence.ClienteRepositorio;
import br.edu.ifnmg.miniMundo.Persistence.FuncionarioRepositorio;
import br.edu.ifnmg.miniMundo.Persistence.ProdutoRepositorio;
import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Edlâine
 */
public class VenderProduto extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmEfetuarVenda
     */
    
    Produto produto = new Produto();
    ProdutoRepositorio repo_produto = new ProdutoRepositorio();
    
    FuncionarioRepositorio repo_func = new FuncionarioRepositorio();
    Funcionario funcionario = new Funcionario();
 
    ClienteRepositorio repo_cliente = new ClienteRepositorio();
    Cliente cliente = new Cliente();
    
    VendaProduto venda = new VendaProduto();
    
    public VenderProduto() {
        produto = new Produto();
        repo_produto = new ProdutoRepositorio();
        repo_func = new FuncionarioRepositorio();
        funcionario = new Funcionario();
        cliente = new Cliente();
        repo_cliente = new ClienteRepositorio();
        venda = new VendaProduto();
        initComponents();
    }
    /*
    private void atualizarProdutos(){
        String[] vendas = new String[venda.getProdutos().size()];
        vendas = venda.getProdutos().toArray(vendas);
        ListModel<String> produtos = new DefaultComboBoxModel<>(vendas) ;
        listProdutos.setModel(produtos);
     }
*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIdentificacaoCliente = new javax.swing.JLabel();
        txtIdentificacaoCliente = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();
        btnAdicionarProduto = new javax.swing.JButton();
        lblSelecionarProduto = new javax.swing.JLabel();
        lblTituloVendas = new javax.swing.JLabel();
        lblQtdDisp = new javax.swing.JLabel();
        txtQtdDisp = new javax.swing.JTextField();
        lblQtdDesejada = new javax.swing.JLabel();
        txtQtdDesejada = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnInserirQtd = new javax.swing.JButton();
        idFuncionario = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        btnValidarUser = new javax.swing.JButton();
        txtProduto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabResultado = new javax.swing.JTable();

        setClosable(true);
        setTitle("Mini Mundo Supermecados - Efetuar Vendas");

        lblIdentificacaoCliente.setText("Insira a identificação do Cliente:");

        txtIdentificacaoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdentificacaoClienteActionPerformed(evt);
            }
        });

        btnBuscarCliente.setText("Validar Cliente");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        btnAdicionarProduto.setText("Adicionar");
        btnAdicionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarProdutoActionPerformed(evt);
            }
        });

        lblSelecionarProduto.setText("Selecione o Produto desejado:");

        lblTituloVendas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTituloVendas.setText("Vendas");

        lblQtdDisp.setText("Qnt Disponível:");

        lblQtdDesejada.setText("Qnt Desejada:");

        jButton1.setText("Concluir Venda");

        btnInserirQtd.setText("Inserir Qtd");

        idFuncionario.setText("Insira o USER do Funcionário:");

        btnValidarUser.setText("Validar Funcionário");
        btnValidarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarUserActionPerformed(evt);
            }
        });

        tabResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Descrição", "Fornecedor", "Unid Compra", "Unid Venda", "Preço Compra", "Preço Venda", "Unidade Compra", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabResultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblIdentificacaoCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdentificacaoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSelecionarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(191, 191, 191)
                                .addComponent(lblTituloVendas))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblQtdDisp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtQtdDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblQtdDesejada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtQtdDesejada, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idFuncionario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnValidarUser)
                                    .addComponent(btnAdicionarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnInserirQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(26, 26, 26))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idFuncionario)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnValidarUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdentificacaoCliente)
                    .addComponent(txtIdentificacaoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelecionarProduto)
                    .addComponent(btnAdicionarProduto)
                    .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInserirQtd)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQtdDisp)
                    .addComponent(txtQtdDisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQtdDesejada)
                    .addComponent(txtQtdDesejada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addGap(35, 35, 35)
                .addComponent(jButton1)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        // TODO add your handling code here:
        cliente = new Cliente();
        
        if(!this.txtIdentificacaoCliente.getText().isEmpty()) {
            cliente.setId(Integer.parseInt(txtIdentificacaoCliente.getText()));
            try {
                cliente = repo_cliente.ValidarId(cliente);
                if(cliente == null)
                    JOptionPane.showMessageDialog(null, "Usuário Inválido!");
                else 
                    JOptionPane.showMessageDialog(null, "Usuário Validado com Sucesso!");
            } catch (ErroValidacaoException ex) {
                Logger.getLogger(VenderProduto.class.getName()).log(Level.SEVERE, null, ex);
            }
        }        
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnAdicionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarProdutoActionPerformed
        // TODO add your handling code here:
       produto = new Produto();
       if(!txtProduto.getText().isEmpty())
           produto.setId(Integer.parseInt( txtProduto.getText() ));
    
        try {
            produto = repo_produto.AbrirProduto(produto);
            if (produto == null)
                JOptionPane.showMessageDialog(null, "Usuário Inválido!");
            else 
                preencherTabela(produto);
        } catch (ErroValidacaoException ex) {
            Logger.getLogger(VenderProduto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(VenderProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAdicionarProdutoActionPerformed

    private void txtIdentificacaoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdentificacaoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdentificacaoClienteActionPerformed

    private void btnValidarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarUserActionPerformed
        // TODO add your handling code here:
        funcionario = new Funcionario();
        
        if(!this.txtUser.getText().isEmpty())
            try {
                funcionario.setUser(txtUser.getText());
                funcionario = repo_func.ValidarUser(funcionario);
                if(funcionario == null)
                    JOptionPane.showMessageDialog(null, "Usuário Inválido!"); 
                else 
                    JOptionPane.showMessageDialog(null, "Usuário Validado com Sucesso!");
            } catch (ErroValidacaoException ex) {
                Logger.getLogger(VenderProduto.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_btnValidarUserActionPerformed

    private void preencherTabela(Produto lista) {
        DefaultTableModel modelo = new DefaultTableModel();
        //adiciona coluna por coluna
        modelo.addColumn("ID");
        modelo.addColumn("Descrição");
        modelo.addColumn("Fornecedor");
        modelo.addColumn("Unid Compra");
        modelo.addColumn("Unid Venda");
        modelo.addColumn("Preço Venda");
        modelo.addColumn("Preço Compra");
        modelo.addColumn("Unid Comprada");
        modelo.addColumn("Status");
        
        Produto prod = null;
        //cria um vetor de linha
        Vector linha = new Vector();
        //adiciona linha por linha
        linha.add(prod.getId());
        linha.add(prod.getDescricao());
        linha.add(prod.getFornecedor());
        linha.add(prod.getUnidCompra());
        linha.add(prod.getUnidVenda());
        linha.add(prod.getPrecoVenda());
        linha.add(prod.getPrecoCompra());
        linha.add(prod.getUnidComprada());
        linha.add(prod.getStatus());
        
        
        //adiciona cada linha na tabela
        modelo.addRow(linha);
                
        //adiciona o modelo que é a minha tabela na tabela da interface
        tabResultado.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarProduto;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnInserirQtd;
    private javax.swing.JButton btnValidarUser;
    private javax.swing.JLabel idFuncionario;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIdentificacaoCliente;
    private javax.swing.JLabel lblQtdDesejada;
    private javax.swing.JLabel lblQtdDisp;
    private javax.swing.JLabel lblSelecionarProduto;
    private javax.swing.JLabel lblTituloVendas;
    private javax.swing.JTable tabResultado;
    private javax.swing.JTextField txtIdentificacaoCliente;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtQtdDesejada;
    private javax.swing.JTextField txtQtdDisp;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

}
